project:
  type: website
  output-dir: docs

website:
  title: "dvaghela - STAT 515 Mid Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - code.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

